### ISSUE TITLE
Traces not showing in UI

### ISSUE THREAD

**Issue by gamblea** [opendistro-for-elasticsearch/trace-analytics#45] opened 2021-05-21 22:13 UTC
Hi,

I have currently setup a Elasticsearch on AWS and a data prepare instance in ec2. I have been able to send open telemetry traces through the data-prepper into the elastic search instance. I am able to view the trace documents and data within the index:  otel-v1-apm-span.

<img width="2136" alt="image" src="https://user-images.githubusercontent.com/24486594/119203030-fa9cf700-ba46-11eb-9ac5-f61be090c38b.png">

Although when I go through Kibana -> Trace Analytics I see an empty dashboard, with only the service map:

<img width="2358" alt="image" src="https://user-images.githubusercontent.com/24486594/119202860-8eba8e80-ba46-11eb-9403-f891ad1a4742.png">

In the bottom right I can see that there are 121 total traces, but I can not view them through trace analytics.

Any help or point me in the right directly for possible fixes would be greatly appreciated.

**Comment by joshuali925** [comment] 2021-05-25 16:50
Hi @gamblea, thanks for filling out an issue. This looks like a version incompatibility issue with data-prepper and trace analytics. To help debugging, which version of trace analytics and data-prepper are you using? And could you dump some documents from `otel-v1-apm-span`? I'll also try to reproduce the problem

**Comment by gamblea** [comment] 2021-05-25 19:17
Hi, I have jus came to the same conclusion. I am using version 1.0 of the Data Prepare and the most recent version of Kibana on AWS. Although AWS does not expose which version of the Trace Analytics is being used. The Kibana version is 7.10.2. 

I have ran the console on trying to access the trace analytics and have seen the following error:

<img width="928" alt="image" src="https://user-images.githubusercontent.com/24486594/119554895-14de1a00-bd52-11eb-9fa5-3567895a7d11.png">


I then went through the index of the traces and found that traceGroup.durationInNanos does not exist.

<img width="424" alt="image" src="https://user-images.githubusercontent.com/24486594/119555041-3fc86e00-bd52-11eb-8fc5-610604424a75.png">

Ignore traceGroup2 I was trying to copy traceGroupFields.durationInNanos into traceGroup.durationInNanos.

Here I have traceGroupFields.duration in the index instead of traceGroup.durationInNanos.  

I assuming that this issue has to do with:

https://github.com/opendistro-for-elasticsearch/trace-analytics/pull/39

and 

https://github.com/opendistro-for-elasticsearch/trace-analytics/pull/39

Is my best course of action to use version 0.8 of the data prepper instead until pull 39 propagates to AWS eventually?

**Comment by joshuali925** [comment] 2021-05-25 19:34
Yes, data-prepper 1.0 made some changes to the schema to fix a compatibility issue on Elasticsearch. The corresponding change in Trace Analytics is not released yet. You can use data-prepper 0.8 and wait for the next managed service release or [opensearch](https://opensearch.org/) release. 

If you just want to try it out, you can also build Trace Analytics from `main` branch of this repo, which works for data-prepper 1.0. instructions [here](https://github.com/opendistro-for-elasticsearch/trace-analytics#setup)

**Comment by gamblea** [comment] 2021-05-25 20:08
Hm I have tried data-prepped 0.8 but it seems to be using a deprecated feature when bringing it up in an EC2 instance and is unable to access the AWS ES domain (v7.10). This stops the data-prepped from being able to start up.

<img width="2190" alt="Screen Shot 2021-05-25 at 12 58 49 PM" src="https://user-images.githubusercontent.com/24486594/119560977-76ee4d80-bd59-11eb-9656-cac417e75fe3.png">

I have ran the Open Distro of Kibana locally but my goal is to be able to use it with the AWS version of Elasticsearch.

Is there any end to end documentation for setting up trace analytics on AWS with running data-prepper in EC2 and AWS ES?

**Comment by gamblea** [comment] 2021-05-25 20:22
It looks like AWS ES deprecated policy_id in version 7.10

**Comment by joshuali925** [comment] 2021-05-25 20:32
Haven't seen this before, @wrijeff any ideas on this error?

**Comment by wrijeff** [comment] 2021-05-25 21:52
Hey @gamblea, thanks for testing out Data Prepper and the Trace Analytics plugin. The most recent AWS deployment has a known bug which blanks out part of the dashboard (as you've already experienced), a fix is coming "soon" but I can't give an exact date unfortunately. It's a bit of a mess, I know 🤕. A few paths for the short term:

####  On Open Distro For Elasticsearch
If you're looking to just test out the trace analytics features, you can deploy the ODFE bundle on your own hardware and use Data Prepper 1.0. I see you've deployed locally before, so this would be an easy, temporary fix for now.

#### On Amazon Elasticsearch Service with Data Prepper 1.0
If you'd rather test the features on AES, then one option is to continue using Data Prepper 1.0 and hang on til the dashboard bug is fixed. You can ingest data and use other parts of the dashboard, but the "trace group" list will continue to be broken until next release. Data Prepper 0.8 can't be used on the latest AES release unfortunately; there's a [compatibility issue](https://github.com/opendistro-for-elasticsearch/index-management/blob/main/release-notes/opendistro-for-elasticsearch-index-management.release-notes-1.13.0.0.md#breaking-changes) that only 1.0 has fixed.

#### On Amazon Elasticsearch Service with a tweaked Data Prepper 1.0
If you need to test all features on AES _now_, then another option would be to make a slight adjustment to the Data Prepper 1.0.x branch and build it locally. Essentially it'd be a revert of [this commit](https://github.com/opendistro-for-elasticsearch/data-prepper/commit/1bb550dd1b740482cd27169d59535fd6f04fe59c) to emit a slightly different document structure. The downside here is that once the dashboard fix comes out, you'd have to clear this data as it's a deviation from DP 1.0.


For getting started with Data Prepper EC2, check out these [AWS docs](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/trace-analytics.html) and this [blog post](https://aws.amazon.com/blogs/big-data/getting-started-with-trace-analytics-in-amazon-elasticsearch-service/) which covers deploying to EC2 with a CloudFormation template. Hope this helps, please let me know if you have any other questions.

**Comment by gamblea** [comment] 2021-05-26 02:35
Hi @wrijeff love the work going on in the project! Really appreciate all the help from you and @joshuali925.

I will try to build the Data Prepper from source with the reverted commit and then run it on EC2. The difference in document structure is not too big of a deal for my use case and it will be fine to throw away the data once the new data comes out.

Since writing the above I had got the Data Prepper compiled from the reverted commit. Ran into a few issues with my version of java and having another elasticsearch running locally that cause the build script to fail. 

Still need to deploy it onto EC2 to test. 

Thanks again for the help! 😃

**Comment by gamblea** [comment] 2021-05-27 20:38
Was able to successfully run the modified data-prepper in EC2 and see traces on AWS ES Kibana.

**Comment by jn1z** [comment] 2021-08-31 18:17
Hi, is there a timeline for the next release?

**Comment by joshuali925** [comment] 2021-09-10 16:50
@jn1z OpenSearch 1.0 is released recently.

Closing this, feel free to reopen if there are further issues.

**Closed by joshuali925** 2021-09-10 16:50 UTC
